/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bakso_gaul;

import javax.swing.*;

/**
 *
 * @author rendti3080
 */
public class home_page extends javax.swing.JFrame {

    public Integer harga1;
    public Integer jumlah1;
    public Integer harga2;
    public Integer jumlah2;
    public Integer harga3;
    public Integer jumlah3;
    public Integer harga4;
    public Integer jumlah4;
    public Integer harga5;
    public Integer jumlah5;
    public Integer harga6;
    public Integer jumlah6;
    public Integer harga7;
    public Integer jumlah7;
    public Integer harga8;
    public Integer jumlah8;

    /**
     * Creates new form home_page
     */
    public home_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        form_baksobrnk = new javax.swing.JTextField();
        form_esklp = new javax.swing.JTextField();
        form_tehmns = new javax.swing.JTextField();
        form_esjrk = new javax.swing.JTextField();
        form_mieahot = new javax.swing.JTextField();
        form_mieabk = new javax.swing.JTextField();
        form_baksotpng = new javax.swing.JTextField();
        form_total = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        total_btn = new javax.swing.JButton();
        form_baksordl = new javax.swing.JTextField();

        jLabel13.setText("Es Jeruk");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setText("Bakso Gaul Perumnas");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 12)); // NOI18N
        jLabel2.setText(" Jalan Bali Raya,Bekasi 081298143378");

        jLabel3.setText("Menu");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah");

        jLabel6.setText("Bakso Rudal");

        jLabel7.setText("Mie Ayam Hot");

        jLabel8.setText("Bakso Beranak");

        jLabel9.setText("Bakso Tumpeng");

        jLabel10.setText("Mie Ayam Bakso");

        jLabel11.setText("Es Teh Manis");

        jLabel12.setText("Es Kelapa");

        jLabel14.setText("Es Jeruk");

        jLabel15.setText("25.000");

        jLabel16.setText("22.000");

        jLabel17.setText("32.000");

        jLabel18.setText("18.000");

        jLabel19.setText("28.000");

        jLabel20.setText("5.000");

        jLabel21.setText("12.000");

        jLabel22.setText("5.000");

        form_baksobrnk.setText("0");
        form_baksobrnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_baksobrnkActionPerformed(evt);
            }
        });
        form_baksobrnk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_baksobrnkKeyTyped(evt);
            }
        });

        form_esklp.setText("0");
        form_esklp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_esklpActionPerformed(evt);
            }
        });
        form_esklp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_esklpKeyTyped(evt);
            }
        });

        form_tehmns.setText("0");
        form_tehmns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_tehmnsActionPerformed(evt);
            }
        });
        form_tehmns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_tehmnsKeyTyped(evt);
            }
        });

        form_esjrk.setText("0");
        form_esjrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_esjrkActionPerformed(evt);
            }
        });
        form_esjrk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_esjrkKeyTyped(evt);
            }
        });

        form_mieahot.setText("0");
        form_mieahot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_mieahotActionPerformed(evt);
            }
        });
        form_mieahot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_mieahotKeyTyped(evt);
            }
        });

        form_mieabk.setText("0");
        form_mieabk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_mieabkActionPerformed(evt);
            }
        });
        form_mieabk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_mieabkKeyTyped(evt);
            }
        });

        form_baksotpng.setText("0");
        form_baksotpng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_baksotpngActionPerformed(evt);
            }
        });
        form_baksotpng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_baksotpngKeyTyped(evt);
            }
        });

        jLabel23.setText("Total");

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        total_btn.setText("Total");
        total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_btnActionPerformed(evt);
            }
        });

        form_baksordl.setText("0");
        form_baksordl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                form_baksordlKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(186, 186, 186))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logout_btn)
                        .addGap(48, 48, 48)))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(92, 92, 92))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 99, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(form_total, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(total_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reset_btn))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(form_esjrk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(form_esklp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_tehmns, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_mieabk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_mieahot, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(form_baksobrnk)
                                    .addComponent(form_baksotpng)
                                    .addComponent(form_baksordl, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(form_baksordl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16))
                    .addComponent(form_baksobrnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_baksotpng, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_mieahot, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_mieabk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_tehmns, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_esklp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(form_esjrk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addComponent(form_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_btn)
                    .addComponent(reset_btn)
                    .addComponent(total_btn))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_baksobrnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_baksobrnkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_baksobrnkActionPerformed

    private void form_esklpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_esklpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_esklpActionPerformed

    private void form_tehmnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_tehmnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_tehmnsActionPerformed

    private void form_esjrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_esjrkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_esjrkActionPerformed

    private void form_mieahotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_mieahotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_mieahotActionPerformed

    private void form_mieabkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_mieabkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_mieabkActionPerformed

    private void form_baksotpngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_baksotpngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_baksotpngActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:
        form_baksordl.setText("0");
        form_baksobrnk.setText("0");
        form_baksotpng.setText("0");
        form_mieahot.setText("0");
        form_mieabk.setText("0");
        form_tehmns.setText("0");
        form_esjrk.setText("0");
        form_esklp.setText("0");
        form_total.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed

    private void total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_btnActionPerformed
        // TODO add your handling code here:
        harga price = new harga();
        Count count = new Count();

        var dataTotalPrice = countAllProduct(price, count);

        form_total.setText(dataTotalPrice.toString());

    }//GEN-LAST:event_total_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new com.mycompany.bakso_gaul.login_app().setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void form_baksordlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_baksordlKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_baksordlKeyTyped

    private void form_baksobrnkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_baksobrnkKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_baksobrnkKeyTyped

    private void form_baksotpngKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_baksotpngKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_baksotpngKeyTyped

    private void form_mieahotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_mieahotKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_mieahotKeyTyped

    private void form_mieabkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_mieabkKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_mieabkKeyTyped

    private void form_tehmnsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_tehmnsKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_tehmnsKeyTyped

    private void form_esklpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_esklpKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_esklpKeyTyped

    private void form_esjrkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_form_esjrkKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_form_esjrkKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    Integer countAllProduct(harga price, Count count) {

        Integer Total = 0;

        harga1 = price.getRudal();
        jumlah1 = Integer.parseInt(form_baksordl.getText());
        Integer Total1 = count.counting(harga1, jumlah1);
        Total += Total1;

        harga2 = price.getBeranak();
        jumlah2 = Integer.parseInt(form_baksobrnk.getText());
        Integer Total2 = count.counting(harga2, jumlah2);
        Total += Total2;

        harga3 = price.getTumpeng();
        jumlah3 = Integer.parseInt(form_baksotpng.getText());
        Integer Total3 = count.counting(harga3, jumlah3);
        Total += Total3;

        harga4 = price.getAyam_hot();
        jumlah4 = Integer.parseInt(form_mieahot.getText());
        Integer Total4 = count.counting(harga4, jumlah4);
        Total += Total4;

        harga5 = price.getAyam_bakso();
        jumlah5 = Integer.parseInt(form_mieabk.getText());
        Integer Total5 = count.counting(harga5, jumlah5);
        Total += Total5;

        harga6 = price.getTeh();
        jumlah6 = Integer.parseInt(form_tehmns.getText());
        Integer Total6 = count.counting(harga6, jumlah6);
        Total += Total6;

        harga7 = price.getKelapa();
        jumlah7 = Integer.parseInt(form_esklp.getText());
        Integer Total7 = count.counting(harga7, jumlah7);
        Total += Total7;

        harga8 = price.getJeruk();
        jumlah8 = Integer.parseInt(form_esjrk.getText());
        Integer Total8 = count.counting(harga8, jumlah8);
        Total += Total8;

        return Total;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField form_baksobrnk;
    private javax.swing.JTextField form_baksordl;
    private javax.swing.JTextField form_baksotpng;
    private javax.swing.JTextField form_esjrk;
    private javax.swing.JTextField form_esklp;
    private javax.swing.JTextField form_mieabk;
    private javax.swing.JTextField form_mieahot;
    private javax.swing.JTextField form_tehmns;
    private javax.swing.JTextField form_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton total_btn;
    // End of variables declaration//GEN-END:variables

}
